- .github/workflows/ci.yml
- README.md
- lib/annotate/parser.rb
- spec/lib/annotate/annotate_routes_spec.rb
Get CI working on the project.
> Make CI green

- .github/workflows/codeql-analysis.yml
- vendor/files/Gemfile
The CodeQL action was not working when it was originally forked. This PR fixes it.
> Fix CodeQL action

- lib/annotate_rb/model_annotator/column_annotation/annotation_builder.rb
- lib/annotate_rb/model_annotator/column_annotation/type_builder.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/annotation_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/type_builder_spec.rb
Some refactoring and added more tests.
> Improve tests for `ColumnAnnotation::*`

- CHANGELOG.md
Changelog generation is a bit funky, but this is the changelog for 4.2.
> Generate changelog for 4.2

- CHANGELOG.md
> Generate changelog for v4.3.0

- CHANGELOG.md
> Generate changelog for v4.3.1

- CHANGELOG.md
> Generate changelog for v4.4.0

- CHANGELOG.md
> Generate changelog for v4.4.1

- lib/annotate_rb/model_annotator/annotation_pattern_generator.rb
> Remove optional arg from `AnnotationPatternGenerator`

- spec/dummyapp/config/routes.rb
- spec/integration/annotate_routes_spec.rb
- spec/templates/routes.rb
This PR adds an integration for annotating routes in a dummy Rails app.
> Add integration test for annotating routes

- CHANGELOG.md
> Generate changelog for v4.5.0

- .github/workflows/ci.yml
- spec/integration/annotate_after_migration_spec.rb
- spec/integration/annotate_file_with_existing_annotations_spec.rb
- spec/integration/annotate_routes_spec.rb
- spec/integration/annotate_single_file_spec.rb
- spec/integration/cli_spec.rb
- spec/integration/rails_generator_install_spec.rb
- spec/integration/rails_generator_update_config_spec.rb
- spec/spec_helper.rb
- spec/support/aruba.rb
This PR does the following:
- Adds integration test isolation
- Makes integration tests run in matrix mode
- DRYs integration tests
> Improve integration tests

- lib/annotate_rb/tasks/annotate_models_migrate.rake
> Add support for data_migrate gem

- lib/annotate_rb/model_annotator/annotated_file/generator.rb
- lib/annotate_rb/model_annotator/annotated_file/updater.rb
- lib/annotate_rb/model_annotator/single_file_annotation_remover.rb
- lib/annotate_rb/model_annotator/single_file_annotator.rb
This PR does a small refactor to tidy up `AnnotatedFile::Generator` and `AnnotatedFile::Updater`.
> Refactor `AnnotatedFile` classes

- lib/annotate_rb/eager_loader.rb
- lib/annotate_rb/model_annotator.rb
- lib/annotate_rb/model_annotator/model_class_getter.rb
- lib/annotate_rb/model_annotator/model_wrapper.rb
- lib/annotate_rb/model_annotator/zeitwerk_class_getter.rb
- spec/dummyapp/app/models/collapsed/example/test_model.rb
- spec/dummyapp/config/initializers/test_zeitwork_collapsed.rb
- spec/dummyapp/db/migrate/20240210100506_create_collapsed_test_models.rb
- spec/integration/annotate_after_migration_spec.rb
- spec/integration/annotate_collapsed_models_spec.rb
- spec/templates/mysql2/collapsed_test_model.rb
- spec/templates/pg/collapsed_test_model.rb
- spec/templates/sqlite3/collapsed_test_model.rb
This PR adds support for using Zeitwerk which:
- supports using collapsed directories
- for Rails applications with Zeitwerk, should speed up annotation because it no longer eager loads
> Add Zeitwerk support

- CHANGELOG.md
> Generate changelog for v4.6.0

- lib/annotate_rb/model_annotator/column_annotation/attributes_builder.rb
- lib/annotate_rb/model_annotator/column_annotation/column_wrapper.rb
- lib/annotate_rb/model_annotator/column_annotation/default_value_builder.rb
- lib/annotate_rb/model_annotator/column_annotation/type_builder.rb
- lib/annotate_rb/options.rb
- lib/annotate_rb/parser.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/column_wrapper_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/default_value_builder_spec.rb
Will resolve https://github.com/drwl/annotaterb/issues/97
> Add configurable classes list with `to_s` representation

- CHANGELOG.md
> Generate changelog for v4.7.0

- CHANGELOG.md
> Generate changelog for v4.7.1

- CHANGELOG.md
> Generate changelog for v4.8.0

- CHANGELOG.md
> Generate changelog for v4.9.0

- .github/ISSUE_TEMPLATE.md
Helps with understanding context around user submitted issues.
> Add database and adapter to issue template

- CHANGELOG.md
> Generate changelog for v4.10.0

- CHANGELOG.md
> Generate changelog for v4.10.1

- CHANGELOG.md
> Generate changelog for v4.10.2

- CHANGELOG.md
> Generate changelog for v4.11.0

- CHANGELOG.md
> Generate changelog for v4.12.0

- spec/dummyapp/app/models/test_child_default.rb
- spec/dummyapp/db/migrate/20240916190235_create_test_child_defaults.rb
- spec/integration/annotate_model_with_foreign_key_spec.rb
- spec/templates/mysql2/test_child_default.rb
- spec/templates/pg/test_child_default.rb
- spec/templates/sqlite3/test_child_default.rb
This PR adds another model with a foreign key/reference to another model to the dummyapp.
> Add model with association and foreign key to dummyapp

- CHANGELOG.md
> Generate changelog for v4.13.0

- CHANGELOG.md
> Generate changelog for v4.14.0

- CHANGELOG.md
> Generate changelog for v4.15.0

- MIGRATION_GUIDE.md
- README.md
- lib/annotate_rb/parser.rb
> Fix for: Misleading pattern examples in documentation for additional_file_patterns

- README.md
Just adding the --with-column-comments documentation to the readme
> chore: add --with-column-comments readme documentation

- CHANGELOG.md
> Generate changelog for v4.19.0

- lib/annotate_rb/route_annotator/base_processor.rb
- spec/lib/annotate_rb/route_annotator/annotator_spec.rb
I found out that the `--frozen` does not work for `routes`, so I fixed it :)
> Honor --frozen option in routes
