drwl/annotaterb

- lib/annotate_rb/cli.rb
- spec/lib/annotate/annotate_models_annotate_model_file_spec.rb
- spec/lib/annotate/annotate_models_annotating_a_file_frozen_spec.rb
- spec/lib/annotate/annotate_models_annotating_a_file_spec.rb
- spec/lib/annotate/annotate_models_get_model_class_spec.rb
- spec/lib/annotate/annotate_models_get_model_files_spec.rb
- spec/lib/annotate/annotate_models_get_patterns_spec.rb
- spec/lib/annotate/annotate_models_parse_options_spec.rb
- spec/lib/annotate/annotate_models_remove_annotation_of_file_spec.rb
- spec/lib/annotate/annotate_models_resolve_filename_spec.rb
- spec/lib/annotate/annotate_models_set_defaults_spec.rb
- spec/lib/annotate/annotate_routes_spec.rb
- spec/support/annotate_test_constants.rb
- spec/support/annotate_test_helpers.rb
The goal is to get CI green so that we can make behavior and structural changes with confidence.
I've found the following sources of test pollution:
- ENV values being written to and not cleaned up between tests
- `Annotate` has the instance variable, `@has_set_defaults`, which can persist between tests
> Get CI consistently green

- .github/workflows/ci.yml
This PR changes the CI action to run every day at midnight UTC. This is done to regularly check if there are any flakes in the test suite.
> Regularly run CI

- README.md
- dummyapp/Gemfile.lock
To assist with any folks migrating over that modified options in `annotate_models.rake` or `annotate_routes.rake` OR used env variables.
> Add configuration instructions to README

- lib/annotate_rb/model_annotator.rb
- lib/annotate_rb/model_annotator/annotation_decider.rb
- lib/annotate_rb/model_annotator/annotation_generator.rb
- lib/annotate_rb/model_annotator/annotator.rb
- lib/annotate_rb/model_annotator/constants.rb
- lib/annotate_rb/model_annotator/file_annotator.rb
- lib/annotate_rb/model_annotator/file_annotator_instruction.rb
- lib/annotate_rb/model_annotator/helper.rb
- lib/annotate_rb/model_annotator/model_file_annotator.rb
- lib/annotate_rb/model_annotator/model_files_getter.rb
- lib/annotate_rb/model_annotator/related_files_list_builder.rb
- lib/annotate_rb/parser.rb
- spec/lib/annotate_rb/annotate_models/annotate_models_annotating_a_file_frozen_spec.rb
- spec/lib/annotate_rb/annotate_models/annotate_models_annotating_a_file_spec.rb
- spec/lib/annotate_rb/model_annotator/annotation_generator_spec.rb
- spec/lib/annotate_rb/model_annotator/model_file_annotator_spec.rb
* Refactors `ModelAnnotator` internals to (hopefully) improve maintainability
* Fixes bugs in old Annotate project that looked at wrong option keys for `excludes_*`
> Refactor ModelAnnotator

- lib/annotate_rb/model_annotator/magic_comment_parser.rb
- spec/lib/annotate_rb/model_annotator/magic_comment_parser_spec.rb
- spec/lib/annotate_rb/model_annotator/single_file_annotator_spec.rb
Add (silent) support for Sorbet comments, `# typed: ...`.
From https://github.com/ctran/annotate_models/pull/966. Credit goes to @matteolc.
> Support Sorbet `typed` magic comment

- spec/lib/annotate_rb/model_annotator/annotation_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/attributes_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/type_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/model_class_getter_spec.rb
- spec/lib/annotate_rb/model_annotator/model_files_getter_spec.rb
- spec/lib/annotate_rb/model_annotator/pattern_getter_spec.rb
- spec/lib/annotate_rb/model_annotator/single_file_annotation_remover_spec.rb
- spec/lib/annotate_rb/model_annotator/single_file_annotator_spec.rb
- spec/support/annotate_test_helpers.rb
`Options.from(...)` combines the passed in options with the defaults which can hide the implicit options that gets passed around. This change will improve clarity and prevent gotchas due to implicit options in tests.
> Change instances of `Options.from` => `Options.new` in tests

- Gemfile
- lib/annotate_rb/model_annotator/magic_comment_parser.rb
- lib/annotate_rb/route_annotator/helper.rb
Adding constraint to the `standard` gem because we don't check in Gemfile.lock. Without this, CI and other people's environments can use differing versions of `standard`.
> Specify `standard` gem version

- README.md
- dummyapp/Gemfile.lock
- dummyapp/db/schema.rb
- dummyapp/lib/tasks/annotate_rb.rake
- lib/generators/annotate_rb/install/templates/annotate_rb.rake
In the old annotate gem, it used to be possible set `ANNOTATE_SKIP_ON_DB_MIGRATE` to `true|t|yes|y|1` to skip the automatic annotation that happens after a Rails db task is run (e.g. `bin/rails db:migrate`). Note that the automatic annotation would only happen if a user installed the rails plugin (done via `rails g annotate_rb:install`).
This behavior got removed when the dependency on ENV was removed. After some feedback, it seems like it's worth adding back to support special development setups or for checks in a CI pipeline.
Note: if you want the updated rake task, you'll have to rerun `rails g annotate_rb:install`.
> Add `ANNOTATERB_SKIP_ON_DB_TASKS` ENV var to skip auto annotations

- dummyapp/Gemfile.lock
- dummyapp/app/models/case.rb
- dummyapp/app/models/task.rb
- dummyapp/app/models/user.rb
- dummyapp/db/migrate/20230613195631_create_cases.rb
- dummyapp/db/migrate/20230613195649_add_complex_cases_to_cases.rb
- dummyapp/db/migrate/20230614220615_add_simple_int_field_to_tasks.rb
- dummyapp/db/migrate/20230614220819_add_simple_bool_to_cases.rb
- dummyapp/db/migrate/20230614221012_add_json_text_field_to_cases.rb
- dummyapp/db/schema.rb
- lib/annotate_rb/model_annotator/column_annotation/annotation_builder.rb
- lib/annotate_rb/model_annotator/column_annotation/attributes_builder.rb
- lib/annotate_rb/model_annotator/column_annotation/column_wrapper.rb
- lib/annotate_rb/model_annotator/column_annotation/type_builder.rb
- lib/annotate_rb/model_annotator/model_wrapper.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/annotation_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/attributes_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/column_wrapper_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/type_builder_spec.rb
Fixes #45. 
When I extracted out column annotation building [1], I changed the way the default value was read. `Model#column_defaults` has the column default values that are casted appropriately, where as `Column#default` is uncasted and straight from the database, most of the time as a String. It's important to note that the various adapters (sqlite, mysql, postgres) implement the columns differently [2], especially as it relates to Column#default and Model#column_default values.
This PR restores parity with the original gem on how defaults are handled. It also adds tests for the various adapters, because the implementations vary under the hood.
As an example, the mysql adapter sets the value for an integer field without a default to be `0` in `Model#column_defaults`, where as sqlite and …
> Prettify column defaults

- spec/lib/annotate_rb/annotate_models/annotate_models_annotating_a_file_frozen_spec.rb
- spec/lib/annotate_rb/annotate_models/annotate_models_annotating_a_file_spec.rb
- spec/lib/annotate_rb/model_annotator/annotation_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/annotation_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/single_file_annotator_spec.rb
Columns that ActiveRecord gives us has String `#names`. Some tests pass in a Symbol name into `mock_column` which is not accurate, so this PR corrects that.
Follows up on: https://github.com/drwl/annotaterb/pull/44#issuecomment-1590016678
> Make tests that use `mock_column` more accurate

- lib/annotate_rb/model_annotator/annotation_builder.rb
- spec/lib/annotate_rb/model_annotator/annotation_builder_spec.rb
The `model_annotator/annotation_builder_spec.rb` contained a LOT of the tests from the original gem. This PR attempts to flatten the original tests and make it easier to understand. After this, it should be easier to extract tests into their proper places.
> Flatten tests in `annotation_builder_spec.rb`

- dummyapp/Gemfile.lock
- lib/annotate_rb/model_annotator/annotation_builder.rb
- lib/annotate_rb/model_annotator/column_annotation/annotation_builder.rb
- lib/annotate_rb/model_annotator/model_wrapper.rb
- lib/annotate_rb/options.rb
- lib/annotate_rb/parser.rb
- spec/lib/annotate_rb/model_annotator/annotation_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/annotation_builder_spec.rb
- spec/lib/annotate_rb/options_spec.rb
- spec/lib/annotate_rb/parser_spec.rb
- spec/support/annotate_test_helpers.rb
This PR makes the following changes:
* Adds support for table comments
* Adds 2 new options keys: `with_column_comments` and `with_table_comments`
* Checks for `with_comment: true, with_column_comments: true` to add column comments
* Checks for `with_comment: true, with_table_comments: true` to add table comments
* Changes `Options#load_defaults`, it defaults `with_column_comments` and `with_table_comments` to use the value set in `with_comment` if not previously set
> Add support for table comments

- lib/annotate_rb/model_annotator/column_annotation/default_value_builder.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/default_value_builder_spec.rb
In https://github.com/drwl/annotaterb/pull/58, it changed the default behavior for unhandled types from `#inspect` to `#to_s`. I didn't consider to add test cases for dates or datetimes which led to a regression.
I tried writing unit tests for it, but realized that it wouldn't work easily because Rails monkey patches `#inspect`:
https://github.com/rails/rails/blob/44bd6e7acaa91dd59c260beea6863a49b84f6039/activesupport/lib/active_support/core_ext/date/conversions.rb#L63-L67
Testing this behavior will be handled in a separate PR.
> Fix annotation for columns with `Date` and `DateTime` default values

- Rakefile
- spec/dummyapp/Gemfile
- spec/integration/annotate_single_file_spec.rb
This PR builds on top of the integration tests in #60 and adds a test for annotating a single file:
`bundle exec annotaterb models app/models/test_default.rb`
> Add integration test for annotating a singular file

- lib/annotate_rb/model_annotator/model_files_getter.rb
- lib/annotate_rb/options.rb
- lib/annotate_rb/parser.rb
- lib/annotate_rb/runner.rb
- spec/lib/annotate_rb/annotate_models/annotate_models_annotating_a_file_spec.rb
- spec/lib/annotate_rb/model_annotator/model_files_getter_spec.rb
This PR removes `ARGV` from being used implicitly during runtime. Before this change, ARGV would be used and modified in `Parser#parse` which made it hard to reason about how `ModelFilesGetter#list_model_files_from_argument` works.
`ARGV` is still used at the time of execution but gets cloned in `Parser#new`.
> Remove `ARGV` use during runtime

- spec/integration/rails_generator_install_spec.rb
This PR adds integration test for the rake task installer. The installer is invoked using this CLI command:
`bin/rails generator annotate_rb:install`
> Add integration test for rake task installer

- spec/integration/annotate_after_migration_spec.rb
- spec/templates/migrations/20231013230731_add_int_field_to_test_defaults.rb
- spec/templates/mysql2/test_default_updated.rb
- spec/templates/pg/test_default_updated.rb
- spec/templates/sqlite3/test_default_updated.rb
This PR adds integration tests for running annotations after a migration:
- Tests manually running annotate models command after a migration
- Tests automatic annotations running after a database migration command
> Test running annotations after a migration

- lib/annotate_rb.rb
- lib/annotate_rb/config_generator.rb
- lib/generators/annotate_rb/config/USAGE
- lib/generators/annotate_rb/config/config_generator.rb
- lib/generators/annotate_rb/hook/USAGE
- lib/generators/annotate_rb/hook/hook_generator.rb
- lib/generators/annotate_rb/hook/templates/annotate_rb.rake
- lib/generators/annotate_rb/install/install_generator.rb
- lib/generators/annotate_rb/install/templates/annotate_rb.rake
- lib/generators/annotate_rb/update_config/USAGE
- lib/generators/annotate_rb/update_config/update_config_generator.rb
- spec/integration/rails_generator_install_spec.rb
- spec/integration/rails_generator_update_config_spec.rb
- spec/lib/annotate_rb/config_generator_spec.rb
- spec/spec_helper.rb
- spec/support/shared_contexts.rb
This PR does the following:
- Adds 3 new rails generator commands: `bin/rails g annotate_rb:hook`, `bin/rails g annotate_rb:config`, and `bin/rails g annotate_rb:update_config`.
- Changes the behavior of the existing `bin/rails g annotate_rb:install` generator.
Previously, the install generator would only copy/install the hook rake file to the Rails project. With this change, it will also generate a default configuration file. 
`bin/rails g annotate_rb:hook`
(Only) adds the rake file to the Rails project.
`bin/rails g annotate_rb:config`
Generates a new configuration file, `.annotaterb.yml`, using defaults from the gem.
`bin/rails g annotate_rb:update_config`
Appends to `.annotaterb.yml` any configuration key-value pairs that are used by the Gem. This is useful when there's a drift …
> Add command to generate a configuration file

- .standard.yml
- spec/integration/annotate_file_with_existing_annotations_spec.rb
- spec/templates/mysql2/test_default_with_bottom_annotations.rb
- spec/templates/pg/test_default_with_bottom_annotations.rb
- spec/templates/sqlite3/test_default_with_bottom_annotations.rb
Adds another integration test passing in commands through the CLI.
> Add integration test using force

- spec/integration/annotate_after_migration_spec.rb
Adding new migrations to `dummyapp` will cause this test to behave unexpectedly. By specifying the migration to migrate will make this test deterministic.
> Improve annotate after adding new migration integration test

- spec/integration/rails_generator_install_spec.rb
- spec/support/aruba.rb
This PR fixes the flakey test in `rails_generator_install_spec.rb`. Before this change, it seems like the `"returns the Thor cli"` test could have unexpected side effects because the `run_command` would not be resolved.
This PR:
- Quits the Thor CLI, aiming to resolve the command
- Changes the database reset command to have fresh databases without any chance of migrations being loaded before tests.
> Fix flakey integration test

- lib/annotate_rb/model_annotator/file_parser/custom_parser.rb
- spec/lib/annotate_rb/model_annotator/annotated_file/generator_spec.rb
- spec/lib/annotate_rb/model_annotator/annotated_file/updater_spec.rb
- spec/lib/annotate_rb/model_annotator/custom_parser_spec.rb
This PR adds support for other Ruby files types that should be able to get model annotations added to them (i.e. factories, fabricators, etc).
In #72, AnnotateRb was changed to use `FileParser::CustomParser` to parse Ruby files instead of relying on regexes. That PR only added support for model files that used either `module Namespace...` or `class ModelName...` as the first line of Ruby. The parser did not have support for other file structures like FactoryBot factories or Fabrication fabricators. 
There may be other Ruby files that have code that is not currently handled by `CustomParser`, so those will have to be added in the future.
> Support non-model files in `CustomParser`

- lib/annotate_rb/model_annotator/related_files_list_builder.rb
- spec/lib/annotate_rb/model_annotator/related_files_list_builder_spec.rb
This PR fixes `RelatedFilesListBuilder` to correctly read the `:active_admin` and `:additional_file_patterns` options. It also adds tests.
> Fixes for `RelatedFilesListBuilder`

- lib/annotate_rb/model_annotator/file_name_resolver.rb
- spec/lib/annotate_rb/model_annotator/file_name_resolver_spec.rb
This PR adds a new wildcard that can be used in the `additional_file_patterns` options. When specifying additional files to get annotated, such as in tests or specs, you can use  `%MODEL_NAME_WITHOUT_NS%` as a wild card.
Example:
```yaml
:additional_file_patterns:
- spec/components/%MODEL_NAME_WITHOUT_NS%_spec.rb
```
> Add support for model name without namespace in resolver

- lib/annotate_rb/model_annotator/file_parser/custom_parser.rb
- spec/lib/annotate_rb/model_annotator/custom_parser_spec.rb
This PR adds support for parsing RSpec files correctly. Prior to this PR, RSpec files would not get annotated correctly.
It adds support for files that use `RSpec.describe` and the `describe` when it gets globally monkey patched.
> Add support for parsing RSpec files

- lib/annotate_rb/model_annotator.rb
- lib/annotate_rb/model_annotator/annotation_builder.rb
- lib/annotate_rb/model_annotator/check_constraint_annotation.rb
- lib/annotate_rb/model_annotator/check_constraint_annotation/annotation_builder.rb
- lib/annotate_rb/options.rb
- lib/annotate_rb/parser.rb
- spec/lib/annotate_rb/model_annotator/annotation_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/check_constraint_annotation/annotation_builder_spec.rb
- spec/lib/annotate_rb/parser_spec.rb
- spec/support/annotate_test_helpers.rb
Supports annotating model check constraints, credit goes to folks who worked on https://github.com/ctran/annotate_models/pull/868.
Adds new option `show_check_constraints` that defaults to `false`. When enabled, it will add check constraints annotations https://github.com/rails/rails/pull/31323 to the model annotations.
It can be enabled also through the command line with options `-c` or `--show-check-constraints`.
Resolves #104
> Annotate model check constraints

- lib/annotate_rb/model_annotator/annotation_decider.rb
In the old gem [1], the conditional for deciding to annotate a file was chained, meaning that execution of further checks stopped upon reaching a false condition. 
The conditional was hard to read, so I decomposed the conditional into readable chunks. This led to a regression, that deciding to annotate a `Module` would raise because `#superclass` is a method on classes, but not for instances of modules. By returning false early, we fix the regression.
To illustrate, before this change one would see this in the output:
```
Unable to process app/models/user_settings/dsl.rb: undefined method `superclass' for module UserSettings::DSL
```
when attempting to annotate a file like:
```ruby
module UserSettings::DSL
module ClassMethods
end
end
```
In the old gem, this error message wouldn't be …
> Change AnnotationDecider to return false early

- lib/annotate_rb/model_annotator/annotation_builder.rb
- spec/lib/annotate_rb/model_annotator/annotation_builder_spec.rb
This PR memoizes the `ActiveRecord::Migrator.current_version` call so that it's only called once per annotaterb run. 
Prior to this change, there would be duplicate separate calls for each model that was being annotated.
> Memoize ActiveRecord migrator version calls

- lib/annotate_rb/model_annotator/check_constraint_annotation/annotation_builder.rb
- spec/lib/annotate_rb/model_annotator/annotation_builder_spec.rb
- spec/support/annotate_test_helpers.rb
Thank you for forking annotate_models, cleaning up the code, and providing further maintenance for it 🙏 
We were about to swap our extremely old fork with check constraint support to annotaterb and noticed that `NOT VALID` constraints are not fully annotated.
For example, one of our model annotations would end up missing the `NOT VALID` portion after migrating:
```diff
diff --git a/app/models/model_name.rb b/app/models/model_name.rb
index f39ff14a38..c7220921cb 100644
--- a/app/models/model_name.rb
+++ b/app/models/model_name.rb
@@ -34,10 +34,10 @@
#
#
-# CHECK Constraints
+# Check Constraints
#
-#  positive_check  ((column_a > 0)) NOT VALID
-#  length_check    ((length(column_b) <= 100000)) NOT VALID
+#  positive_check  (column_a > 0)
+#  length_check    (length(column_b) <= 100000)
# …
```
> Add support for `NOT VALID` constraints

- lib/annotate_rb/model_annotator/foreign_key_annotation/annotation_builder.rb
- spec/lib/annotate_rb/model_annotator/foreign_key_annotation/annotation_builder_spec.rb
This PR adds support for composite foreign keys. Credit goes to @carldr for https://github.com/ctran/annotate_models/pull/1013.
Closes #121.
> Support composite foreign keys

- lib/annotate_rb/model_annotator/annotation_decider.rb
In our project we have more than just Active Record models within our `models` folder. After switching to this gem we noticed a couple errors being raised when attempting to decide if some of those should be annotated or not.
For example, a class that inherits from `Dry::Struct` responds to `abstract_class` but not to `abstract_class?`.
```ruby
> class Demo < Dry::Struct; end
> Demo.abstract_class
=> Dry::Struct
> Demo.abstract_class?
(irb):3:in `<main>': undefined method `abstract_class?' for class Demo (NoMethodError)
```
> Correct uses of `respond_to` in AnnotationDecider

- lib/annotate_rb/rake_bootstrapper.rb
See #130 for problem discussion.
This also drops a lot of legacy and/or unnecessary code from `AnnotateRb::RakeBootstrapper`.
> Fix double-loading of Rakefile

- .github/workflows/ci.yml
- spec/integration/rails_generator_install_spec.rb
This PR adds Ruby 3.3 to CI. It also changes the timeout for an integration test case because it seemed to fail on Ruby 3.3, presumably due to Ruby 3.3 running slower.
> Add Ruby 3.3 to CI

- lib/annotate_rb/model_annotator/model_wrapper.rb
- spec/lib/annotate_rb/model_annotator/model_wrapper_spec.rb
close: #144 
By including the length of comments in max_schema_info_width only when both the with_comment and with_column_comments options are true, we can avoid creating unnecessary space between the column and data type.
> Include the length of comments in max_schema_info_width only when the with_comment and with_column_comments option is true.

- lib/annotate_rb/model_annotator/index_annotation/index_component.rb
- spec/lib/annotate_rb/model_annotator/annotation/annotation_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/index_annotation/annotation_builder_spec.rb
- spec/support/annotate_test_helpers.rb
Postgres supports NULLS NOT DISTINCT for unique indexes https://www.postgresql.org/docs/current/indexes-unique.html#INDEXES-UNIQUE
This causes the index to treat nulls as equal which is important information to surface when one of the columns is nullable. 
This utilizes `nulls_not_distinct` in the [index definition](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/IndexDefinition/new/class) to surface this information
> Support postgres NULLS NOT DISTINCT clause in unique index

- lib/annotate_rb/model_annotator/annotated_file/updater.rb
- spec/lib/annotate_rb/model_annotator/annotated_file/updater_spec.rb
There are a number of different mechanisms with [String#sub](https://ruby-doc.org/core-2.4.5/String.html#method-i-sub) that pertain to the matching of backreferences and capture groups when using either the String or Hash type args for the replacement arg.
>If replacement is a String that looks like a pattern's capture group but is actually not a pattern capture group e.g. "\'", then it will have to be preceded by two backslashes like so "\\'".
When an index contains unescaped characters, those are being incorrectly interpreted as capture groups. Using the block version of #sub avoids this.
For example, here's the behaviour we see with an index containing special characters that need escaping.
Existing index:
```
```
Updated index:
```
```
This becomes a problem given that the issue is in …
> Fix updating of indexes containing escaped characters

- lib/annotate_rb/model_annotator/file_parser/yml_parser.rb
- spec/lib/annotate_rb/model_annotator/file_parser/yml_parser_spec.rb
- spec/lib/annotate_rb/model_annotator/single_file_annotator_spec.rb
This PR adds support for dynamic fixtures, which are yml files with Ruby code in them. Rails supports this so we also want to support this.
Before this change, Ruby's yml parser, Psych, would raise `Psych::SyntaxError` when attempting to parse non-valid yml. This change attempts to parse yml normally, but if it fails will run the input through the Erb evaluator and then attempt to parse the output using Psych.
Addresses #149
> Support parsing of dynamic fixture erb yml files

- annotaterb.gemspec
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
> Opt-in for MFA requirement

- spec/dummyapp/Gemfile
To address compatibility issues with Rails 7.0, this commit locks `concurrent-ruby` gem to version 1.3.4.
This change is necessary to prevent an uninitialized constant error related to `ActiveSupport::LoggerThreadSafeLevel::Logger`, as documented in issue rails/rails#54260.
By specifying this version, we ensure that our CI integration specs pass consistently, providing a stable development and testing environment.
This measure will remain in place until the integration tests upgrade to Rails 7.1, which involves significant changes that require careful consideration and testing.
> Lock `concurrent-ruby` gem to fix CI

- lib/annotate_rb/model_annotator/model_wrapper.rb
- spec/dummyapp/.rbenv-gemsets
- spec/lib/annotate_rb/model_annotator/annotation/annotation_builder_spec.rb
I ran into a bug with this logic when using annotaterb + globalize:
For compound names for models such as "ABCustomer", it resulted in "abcustomer_id" being added to the exclusion list, where the actual foreign key name was "ab_customer_id". 
Therefore it was not excluded. And therefore all the annotations for ABCustomer ended up including "ab_customer_id" even though that wasn't an actual column.
This PR includes changes to the unit tests to not break them. However it didn't seem like this bug something I could actually reproduce with the unit tests. I couldn't get the integration test suite working and couldn't spend more time on it right now.
> Fix translation foreign key exclusion bug

- lib/annotate_rb/parser.rb
- spec/lib/annotate_rb/parser_spec.rb
Thank you for developing such a awesome gem. 👍 
In this PR, I have worked on the TODO comment at the following location:
https://github.com/drwl/annotaterb/blob/7746f54b31674603b671db2433cd3d2e3da78fb7/lib/annotate_rb/parser.rb#L84
I have added an alert message indicating that only one command will be executed when multiple commands are specified.
Additionally, the following section did not enter the conditional branch, so I moved it above `if @commands.any?`.
If you have any better approaches, I would appreciate your suggestions.
> Chore: alert when multiple conmmands were selected

- lib/annotate_rb/model_annotator/annotation_diff_generator.rb
- spec/lib/annotate_rb/model_annotator/annotation_diff_generator_spec.rb
Before: Try fail Regex Link https://rubular.com/r/fMCSHSUICtyUIN
After: Try pass Regex LInk https://rubular.com/r/nwANf5UyNf7OhB
close https://github.com/drwl/annotaterb/issues/169
AnnotateRb was not working when column comments included characters like / or non-English characters such as Japanese.
This PR resolves the issue by extending the regular expression to support a wider range of characters in the metadata inside parentheses.
```ruby
COLUMN_PATTERN = /^#[\t ]+[\w*.`\[\]():]+(?:\(.*?\))?[\t ]+.+$/
```
With this regular expression, the test cases added in this pull request fail.
```ruby
❯ be rspec spec/lib/annotate_rb/model_annotator/annotation_diff_generator_spec.rb:146
Run options: include {:locations=>{"./spec/lib/annotate_rb/model_annotator/annotation_diff_generator_spec.rb"=>[14 …
```
> Updated COLUMN_PATTERN to handle optional metadata (e.g., constraints or descriptions) enclosed in parentheses.

- lib/annotate_rb/model_annotator/column_annotation/attributes_builder.rb
- lib/annotate_rb/model_annotator/column_annotation/column_wrapper.rb
- lib/annotate_rb/model_annotator/column_annotation/type_builder.rb
- lib/annotate_rb/options.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/attributes_builder_spec.rb
- spec/lib/annotate_rb/model_annotator/column_annotation/type_builder_spec.rb
Hi there 👋 
Thanks for this active fork! I had a personal fork with some changes for the longest time.
One of these changes was support for [virtual/generated columns](https://guides.rubyonrails.org/active_record_postgresql.html#generated-columns). 
At the moment, the following table would create a slightly confusing annotation
```ruby
create_table :users do |t|
t.string :name
t.virtual :name_upcased, type: :string, as: "upper(name)", stored: true
end
```
```ruby
#
class User < ApplicationRecord
```
With these changes, this would generate the following:
```ruby
#
class User < ApplicationRecord
```
I wasn't a 100% sure where you'd want these changes exactly. I'm happy to make further changes, or add some more tests.
One additional change could be to also place the function in the …
> Add support for virtual columns

- annotaterb.gemspec
This repository uses `main` for the default branch. This can reduce a redirect when accessing the URI.
> Fix `changelog_uri` in gemspec

- lib/annotate_rb/model_annotator/model_wrapper.rb
- lib/annotate_rb/options.rb
- spec/lib/annotate_rb/model_annotator/annotation/annotation_builder_spec.rb
- spec/lib/annotate_rb/options_spec.rb
I'm working with a codebase that doesn't use Rails' default timestamp columns, so being able to customise those would be helpful. This adds `timestamp_columns` as a configurable option for classified sorting, and sorts them in config order rather than alphabetical order.
> feat: add `timestamp_columns` config option

- lib/annotate_rb/model_annotator/project_annotator.rb
We have a pretty large monolith (as well as a second database host that tends to get bogged down after it runs for a while in development), so we find it useful to see some progress indicator while annotations are running.
This adds them in for each model when debug is set. This uses `puts` to match the current debug log that exists.
> Add debug logs for model annotation

- lib/annotate_rb/model_annotator/model_wrapper.rb
When upgrading rails project with 200+ models from annotate to this gem (thanks for creating and maintaining it!), we noticed that annotation became a lot slower. We managed to pinpoint the problem to `indexes = @klass.connection.indexes(table_name)` which was invoked from `AnnotationBuilder::Annotation#columns`  for every column of every model.
Original annotate:
```
bundle exec annotate --models  7,72s user 0,82s system 68% cpu 12,553 total
```
Before this change:
```
bundle exec annotaterb models  27,14s user 2,19s system 60% cpu 48,816 total
```
After this change:
```
bundle exec annotaterb models  7,22s user 0,82s system 82% cpu 9,748 total
```
> Cache retrieved indexes in ModelWrapper

- Gemfile
- annotaterb.gemspec
Moves dependencies from Gemfile into gemspec file. Makes the dependency on activesupport explicit.
> Move activerecord dependency into gemspec

- MIGRATION_GUIDE.md
- README.md
- lib/annotate_rb/config_loader.rb
- spec/lib/annotate_rb/config_loader_spec.rb
Hi!
This PR proposes passing `.annotaterb.yml` through ERB, as Rails does with `config/database.yml` or fixtures, for instance.
Real use case is the ability to compute `model_dir` dynamically. As you know, in `annotate` the configuration can be expressed in Ruby, and therefore it can be as dynamic as you need to. But if you migrate to `annotaterb`, that is lost.
I wrote this patch on behalf of a client of mine (Gusto), whose main application has more than two hundred model dirs. They are now hard-coded in `.annotaterb.yml`, but you need to maintain that list, verify consistency in CI, etc. On the other hand, if you could compute the list in the config file itself, you could forget about it (as it was the case with `annotate`).
I have created a test suite for `load_config`, and …
> Pass .annotaterb.yml through ERB

- lib/annotate_rb/runner.rb
- spec/lib/annotate_rb/runner_spec.rb
This is so that we can facilitate dynamic logic during the annotation process.
This is something that the historical `annotate_models` gem provided, via `Annotate::Migration.class_variable_get(:@@working))`
https://github.com/ctran/annotate_models/blob/5d01c4171990c4fe7b9b0977b05ce14a98209e53/lib/tasks/annotate_models_migrate.rake#L36-L41
Instead of having to reach into the Migration class, this instead stores some state on the `AnnotateRb::Runner` class so that we can ask it directly if it's in the middle of running.
> Add AnnotateRb::Runner.running? method

- lib/annotate_rb/model_annotator/annotation_decider.rb
While looking for a fix for #172 I noticed that `AnnotationDecider` does a fair amount of checks before checking that _all_ are true. We can speed up the decision making a bit and avoid the current issue with `AssociatedObject` completely if we return false early whenever a check fails instead of collecting all the results and then returning false.  It's not the prettiest code but it works and is faster (slightly) on a benchmark:
```
Comparison:
NewAnnotationDecider#annotate?:          30189.7 i/s
OriginalAnnotationDecider#annotate?:    18295.3 i/s - 1.65x  slower
```
I'm aware that the issue posted in #172 Is actually an issue with the `AssociatedObject` gem so no worries if you don't want to merge this.
> Speed up AnnotationDecider

- lib/annotate_rb/model_annotator/model_files_getter.rb
- spec/lib/annotate_rb/model_annotator/model_files_getter_spec.rb
Currently, when there are no available models, `ModelFilesGetter` returns `nil` but callers are expecting it to return an array.
This makes the app crash with:
```
/home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/model_annotator/project_annotator.rb:13:in `annotate': undefined method `map' for nil (NoMethodError)
annotation_instructions = project_model_files.map do |path, filename|
^^^^
from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/model_annotator/annotator.rb:21:in `do_annotations'
from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/model_annotator/annotator.rb:8:in `do_annotations'
from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/commands/annotate_models. …
```
> Return a model files array even if it’s empty

- lib/annotate_rb/model_annotator/annotation/annotation_builder.rb
- lib/annotate_rb/model_annotator/model_wrapper.rb
I really appreciate you taking the time to maintain this project.
Refactored by moving the method added in #241 to the ModelWrapper class for the following reasons:
- Moves migration version retrieval and caching logic to ModelWrapper
- Improves code organization by centralizing database connection operations
- Maintains existing multi-database caching behavior with connection pool names
- Enhances consistency with other database-related methods in ModelWrapper
No functional changes.
> refactor: relocate migration_version_for_model method to ModelWrapper

- spec/dummyapp/config/database.yml
- spec/support/database_contexts.rb
This commit enhances the RSpec test environment to support both single and multi-database configurations.
The next feature to be implemented is conditional model annotations, which requires asserting behavior in two different scenarios:
1. The annotation is added in a multi-DB environment.
2. The annotation is not added in a single-DB environment.
The existing test suite only supported a multi-DB setup, making it impossible to validate the second scenario.
- The database.yml for the dummy app is updated to use an environment variable (SINGLE_DB_TEST). This allows it to conditionally exclude the secondary database configuration.
- A new RSpec shared_context ("when in a single database environment") is introduced. This provides specs with a clean, reusable way to enable the single-database …
> chore: introduce switchable DB environment for specs

- lib/annotate_rb/config_generator.rb
- spec/lib/annotate_rb/config_generator_spec.rb
Hello! :wave: I was poking around the codebase and found this cool `update_config` generator. I gave it a run and found that it resulted in a YAML syntax error. So here's a quick fix!
The `annotate_rb:update_config` generator was appending an empty hash `{}` to the configuration file when all default configuration keys were already present, causing a YAML syntax error.
**Before:**
```yaml
:root_dir:
- '' {}
```
**After:**
```yaml
:root_dir:
- ''
```
In `lib/annotate_rb/config_generator.rb`, the `unset_config_defaults` method would:
1. Compare user config with defaults to find missing keys
2. Create a result hash with missing keys
3. When no keys were missing, `result` would be an empty hash `{}`
4. `YAML.dump({})` produces `--- {}\n` which gets appended to the config file
Added an early …
> fix: resolve YAML syntax error in update_config generator
